let data = [
    {
        title: "Trilho Azul de Monsanto",
        type: "Park",
        description: "Discover paradise with your furry friend on the Blue Trail of Monsanto! Nestled in the heart of Lisbon's Monsanto Forest Park, this trail offers stunning views and endless nature. At around 7.7 km, it's perfect for longer adventures with your dog, exploring the area's amazing biodiversity.",
        link: "https://maps.app.goo.gl/UwipUz4JVsMsrmEr5",
        ImageUrl: "assets/images/trilho_monsanto.png",
        tags: "pet dog free lisbon parque cão cao cachorro gratuito lisboa portugal",
    },
    {
        title: "Praia da Amoreira",
        type: "Beach",
        description: "This is a pet-friendly beach located in the city of Santa Cruz. Among several beaches in the region, this one is exclusive for pets. The beach is very popular with surfers and other water sports enthusiasts, but it also offers quiet spaces for walks and leisure time.",
        link: "https://maps.app.goo.gl/Brwx6W255Qm2v1tH6",
        ImageUrl: "assets/images/praia_amoreiras.png",
        tags: "pet dog free lisbon praia cão cao cachorro gratuito lisboa torres vedras portugal",
    },
    {
        title: "Albufeira do Rio da Mula",
        type: "Lagoon",
        description: "A beautiful lagoon within the Quinta do Pisão in Sintra-Cascais Natural Park. This pet-friendly spot offers stunning natural scenery, perfect for a relaxing day with your furry companion. Enjoy a walk around the lagoon, go for a swim (check for pet restrictions beforehand), or simply soak up the sun.",
        link: "https://maps.app.goo.gl/cCRAyCgW2Pti5ufb8",
        ImageUrl: "assets/images/albufeira_do_rio_da_mula.png",
        tags: "pet dog swin free lago lagoa cão cao cachorro nadar gratuito portugal",
    },
    {
        title: "Praia da Cresmina",
        type: "Beach",
        description: "A haven in the Cascais region for you and your pet to enjoy a day at the beach. With ample space, crystal clear waters, and stunning natural scenery, the beach offers everything you need to relax and have fun with your four-legged companion. In addition, the beach has complete infrastructure, including a restaurant, bar, and first aid station, ensuring comfort and safety.",
        link: "https://maps.app.goo.gl/6RscwyrJ6cNTifnv9",
        ImageUrl: "assets/images/praia_da_cresmina.png",
        tags: "pet dog free praia cão cao cachorro gratuito portugal",
    },
    {
        title: "Quinta da Alfarrobeira",
        type: "Park",
        description: "A green haven in the heart of Lisbon, this is the perfect place for you and your pet to enjoy some leisure time and get in touch with nature. Located in the São Domingos de Benfica region, this historic park offers green spaces that are ideal for walking and playing with your dog. Quinta da Alfarrobeira is a true urban oasis with a rich history and charming landscaping.",
        link: "https://maps.app.goo.gl/RexdgYeYTgQ18Ugc8",
        ImageUrl: "assets/images/quinta_alfarrobeira.png",
        tags: "pet dog free praia cão cao cachorro gratuito lisboa portugal",
    },
    {
        title: "Praia do Barranquinho",
        type: "Beach",
        description: "A paradise for you and your best friend, this is the first official dog beach in Portugal! Located in the Lagoa region of the Algarve, this extensive area of ​​around 80 meters offers a safe and exclusive space for your dog to have fun in the sea and on the sand.",
        link: "https://maps.app.goo.gl/d4tSTvZqke9RsUg79",
        ImageUrl: "assets/images/praia_barranquinho.png",
        tags: "pet dog free praia cão cao cachorro gratuito portugal",
    },
    {
        title: "Parque Canino Alameda Keil do Amaral",
        type: "Park",
        description: "This space is dedicated to dog lovers, with an area of ​​10,000 m² where pets can play and exercise freely. The park also offers tables for humans to have picnics and a skate park for extra fun.",
        link: "https://maps.app.goo.gl/HU3HkPk7LZ2EtmjB6",
        ImageUrl: "assets/images/parque_canino_alameda_keil_amaral.png",
        tags: "pet dog exclusive free lisbon parque cão cao cachorro gratuito monsanto lisboa exclusivo portugal",
    },
    {
        title: "Praia Fonte da Telha",
        type: "Beach",
        description: "One of the postcards of Costa da Caparica, it is a destination that combines natural beauty, tranquility, and fun. With a vast stretch of sand, lush dunes, and a sea of ​​crystal clear waters, this beach offers the perfect setting to enjoy a sunny and relaxing day. Although it isn't an officially designated dog-friendly beach.",
        link: "https://maps.app.goo.gl/x48zPPy9D8WVDPN68",
        ImageUrl: "assets/images/praia_fonte_telha.png",
        tags: "pet dog free almada praia cão cao cachorro gratuito portugal",
    },
];